theme="monokai_pro"
[editor]
line-number = "relative"
mouse = true

[editor.indent-guides]
render = true
character = "│"


[keys.normal]
esc =["collapse_selection" , "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
